(define (lower_bound x) (car x))
(define (upper_bound x) (cdr x))
(define (make_interval a b) (cons a b))
(define (add_interval x y)
    (make_interval (+ (lower_bound x) (lower_bound y))
                   (+ (upper_bound x) (upper_bound y))))
(define (sub_interval x y)
    (make_interval (- (lower_bound x) (upper_bound y))
                   (- (upper_bound x) (lower_bound y))))
(define (print_interval x)
    (newline)
    (display "(")
    (display (lower_bound x))
    (display ",")
    (display (upper_bound x))
    (display ")"))
(define (make_center_percent c p)
    (make_interval (- c (* c 0.01 p))
                   (+ c (* c 0.01 p))))
(define (center x)
        (/ (+ (lower_bound x) (upper_bound x)) 2))
(define (width x)
        (/ (- (upper_bound x) (lower_bound x)) 2))
(define (percent x)
        (* (/ (width x) (center x)) 100))
(print_interval (make_center_percent 5 50))
(center (make_center_percent 5 50))
(percent (make_center_percent 4 35))
(print_interval (make_center_percent 4 25))
(print_interval (add_interval (make_center_percent 5 50) (make_center_percent 4 25)))