(define (make_account balance)
    (define (Invalid_password m)
        "invalid password")
    (define (call_the_cops m)
        "call the cops")
    (define (withdraw amount)
        (if (>= balance amount)
            (begin (set! balance (- balance amount))
                    balance)
            "Insufficient funds"))
    (define (deposit amount)
        (set! balance (+ balance amount))
        balance)
    (define (dispatch password message)
        (if (eq? password `secret_password)
            (cond ((eq? message `withdraw) withdraw)
                  ((eq? message `deposit) deposit)
                  (else
                    (error "Unknown request -- MAKE_ACCOUNT" m)))
            Invalid_password))
    dispatch)
(define acc (make_account 100))
((acc `secret_password `withdraw) 200)
((acc `incorrect_password `withdraw) 200)

