(define (estimate_pi trials)
    (* 4 (monte_carlo trials cesaro_test)))
(define (cesaro_test)
    (<= (+ (square (- (random 2.0) 1)) (square (- (random 2.0) 1))) 1))
(define (monte_carlo trials experiment)
    (define (iter trials_ramaining trials_passed)
        (cond ((= trials_ramaining 0)
                (/ trials_passed trials))
              ((experiment)
                (iter (- trials_ramaining 1) (+ trials_passed 1)))
              (else
                (iter (- trials_ramaining 1) trials_passed))))
    (iter trials 0))
(estimate_pi 10000000)