(define (memq item x)
    (cond ((null? x) false)
          ((eq? item (car x)) x)
          (else (memq item (cdr x)))))
(memq 'apple '(banana (apple car) desk map (apple car)))
(car '(1 2 3))
(pair? (car `(a short list)))
(memq `red `((red shoes) (blue socks)))
(memq `red `(red shoes blue socks))
